- res/openvpn-gui-res-ru.rc
per https://community.openvpn.net/openvpn/ticket/446
> russian language fixes

- misc.c
- misc.h
- openvpn-gui-res.h
- openvpn.c
- registry.c
- res/openvpn-gui-res-en.rc
First two commits address issues discussed in 
http://article.gmane.org/gmane.network.openvpn.devel/11051
http://article.gmane.org/gmane.network.openvpn.devel/11060
The third commit fixes the path to notepad.exe
> Registry and admin

- README
- main.c
- openvpn-gui-res.h
- res/openvpn-gui-res-en.rc
- res/openvpn-gui-res-pt.rc
- tray.c
- tray.h
Hi. I think an option like this might improve the user experience. I myself didn't know I had to put the ovpn files in a "config" folder when I downloaded OpenVPN the first time. It took me a while to figure this out. The code I'm proposing simply launches an "Open File" dialog and then copy the chosen file to the correct directory.
> Add "Import file" menu option

- configure.ac
URL: https://github.com/OpenVPN/openvpn-gui/pull/16
> Bump version in "master" branch to 11

- res/openvpn-gui-res-pt.rc
Updating one more translation, following @selvanair's suggestion at PR #30.
> Improving PT translation

- res/openvpn-gui-res-nl.rc
This PR improves many Dutch texts.
> Improve many Dutch translations

- res/openvpn-gui-res-nl.rc
As mentioned in #30 some text where still missing. This adds
all those texts and adds the texts that were added by #26 as well.
> Add all missing texts and translate them.

- res/openvpn-gui-res-nl.rc
As @syzzer correctly noticed in #34 I included two typos in that PR.
And I also did some minor rewording in the sentences.
@syzzer, could you please check my work, so we don't need yet another PR?
> Fix typos and reword on some texts

- misc.c
- openvpn.c
- registry.c
Broken into 4 commits: only the 3rd one fixes a bug that is easy to reproduce (try an empty password with static challenge).
@soarqin could you please check it doesn't break the rest of the static challenge code?
> Some small bug fixes

- BUILD.rst
At the moment only building on Cygwin is described.
Other ways to build the project, like [MSYS2](https://msys2.github.io/) or cross-compiling on Linux (maybe even using the very much in beta [Bash on Ubuntu on Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/about)), can be added in a later stage.
About the text... know that English is not my native tongue.
> Add build description

- localization.c
- localization.h
- main.c
- openvpn-gui-res.h
- res/openvpn-gui-res-de.rc
- res/openvpn-gui-res-dk.rc
- res/openvpn-gui-res-en.rc
- res/openvpn-gui-res-es.rc
- res/openvpn-gui-res-fi.rc
- res/openvpn-gui-res-fr.rc
- res/openvpn-gui-res-it.rc
- res/openvpn-gui-res-jp.rc
- res/openvpn-gui-res-nl.rc
- res/openvpn-gui-res-no.rc
- res/openvpn-gui-res-pl.rc
- res/openvpn-gui-res-pt.rc
- res/openvpn-gui-res-ru.rc
- res/openvpn-gui-res-se.rc
- res/openvpn-gui-res-tr.rc
- res/openvpn-gui-res-ua.rc
- res/openvpn-gui-res-zh-hant.rc
Hi. I've been missing this setting and I think it could be an useful feature for the end user.
> Launch on startup setting

- openvpn.c
**How to test:**
Using the current GUI and interactive service, start a connection
that needs user-auth. While that dialog is open press the exit button 
from the tray menu. The GUI will exit after waiting for a few seconds but 
the openvpn.exe process will be left behind (will have to be killed manually 
before a new connection can be made). This patch should fix it.
**Commit message:**
PostThreadMessage used to trigger exit event gets lost while
in modal loops such as auth dialog. Replace it by PostMessage
and handle it in the status window callback.
Fixes openvpn processes left behind if exit is pressed while
user-auth dialog is active.
> Fix exit handling while in modal loops

- res/openvpn-gui-res-it.rc
> Fix Italian typo

- openvpn-gui-res.h
- openvpn.c
See commit messages for details
> Some bug fixes

- res/openvpn-gui-res-en.rc
After some creative use of forced pushes, remotes and branching my original pull request (https://github.com/OpenVPN/openvpn-gui/pull/88) went up in a smoke. So here is an amended version that also incorporates feedback from @selvanair . I also linked to OpenVPN-GUI's GitHub page instead of openvpn.net: that should make it more obvious who the "OpenVPN GUI contributors" are. 
> Update About page

- configure.ac
> Preparing for release with openvpn-2.4_beta1

- res/openvpn-gui-res-no.rc
Translated new keys. Improved language, typos and grammar.
> Update Norwegian translation

- res/openvpn-gui-res-de.rc
- res/openvpn-gui-res-dk.rc
- res/openvpn-gui-res-en.rc
- res/openvpn-gui-res-es.rc
- res/openvpn-gui-res-fi.rc
- res/openvpn-gui-res-fr.rc
- res/openvpn-gui-res-it.rc
- res/openvpn-gui-res-jp.rc
- res/openvpn-gui-res-nl.rc
- res/openvpn-gui-res-no.rc
- res/openvpn-gui-res-pl.rc
- res/openvpn-gui-res-pt.rc
- res/openvpn-gui-res-ru.rc
- res/openvpn-gui-res-se.rc
- res/openvpn-gui-res-tr.rc
- res/openvpn-gui-res-ua.rc
- res/openvpn-gui-res-zh-hant.rc
- Copyright update by commit 32c31ab942d in English
copied to other language files.
(except Ukranian for which a PR is pending)
- Changed version displayed in About page to the form
"a.b.c.d"
> Copy updated copyright to language files

- README.rst
> Documentation improvements

- res/openvpn-gui-res-cs.rc
- res/openvpn-gui-res.rc
Czech translation added. I compiled it successfully and tinkered around with radio button positions and widths. I believe it is tested as much as possible and fine to go.
> Czech translation added

- README.rst
- appveyor.sh
* AppVeyor: add shebang
Fix indention.
Not sure if there is a reason to omit it...
* Readme: add AppVeyor badge
So that you can navigate to the page and get the artifacts easily.
Page in action: https://github.com/Chocobo1/openvpn-gui/tree/appveyor#openvpn-gui
There are 2 minor things beside this PR:
1. `appveyor.yml` can actually be renamed to `.appveyor.yml`, if you want coherent naming with `.travis.yml`.
2. The artifact should be able to be compressed to zip (example: https://github.com/RPCS3/rpcs3/blob/master/appveyor.yml#L38) or to 7z (with custom command) if you want...
> Appveyor small improvements

- res/openvpn-gui-res-de.rc
combined the two previous PRs into one
> german translation

- configure.ac
> Bump version to 11.8.0.0

- BUILD.rst
Added an instruction how to build openvpn-gui using MSYS2
> Add instruction how to build using MSYS2

- openvpn.c
Change text colour of log lines flagged as Warning, Nonfatal error and Fatal error.
Colours defined by clr_warning and clr_error introduced in a previous patch are
used. Both of these are currently set as colour "red".
> Highlight warning and error messages in status window

- .travis-build-openssl.sh
- .travis.yml
also include changes from PR#176 to avoid merge conflict
> travis-ci: add openssl-1.1.0 support

- res/openvpn-gui-res-de.rc
This PR completes the german translation and fixes some minor things.
> Update german translation

- misc.c
- misc.h
- openvpn.c
- options.h
- tray.c
> Show assigned ipv6 address in balloon and tray popup

- TODO
It is obsolete and the tasks in there are best tracked locally or in GitHub
issues.
URL: https://github.com/OpenVPN/openvpn-gui/pull/225
> Get rid of TODO

- res/openvpn-gui-res-nl.rc
Recently, there were some new resources added. This PR contains the Dutch translations for them.
The PR also features some minor changes in the current translations.
> Add Dutch translations for recently added resources

- Makefile.am
- res/openvpn-gui-res-zh-hans.rc
- res/openvpn-gui-res.rc
add Chinese (Simplified) localization
build test on msys2
test on Windows 10 x64
> add Chinese (Simplified) localization

- misc.c
- openvpn.c
- tray.c
> Clear c->ip and c->ipv6 buffers before reset

- res/openvpn-gui-res-kr.rc
synchronized the korean resource file with the english version
> update korean resource file

- res/openvpn-gui-res-it.rc
Updated missing strings, in addition to various corrections and general improvements/clarifications. Some of the strings still sound a bit "off", but this should represent a 99% complete localization.
> Updated Italian localization

- BUILD.rst
- openvpn.c
- set focus to auth challenge field if it is present and the password has already been filled
- remove unnessary cygwin package mingw64-x86_64-gcc-g++
> set focus to challenge when password already filled

- .appveyor.yml
- .gitignore
- config-msvc.h
- main.c
- main.h
- openvpn-gui.sln
- openvpn-gui.vcxproj
- openvpn-gui.vcxproj.filters
- res/openvpn-gui-res-en-msvc.rc
- res/openvpn-gui-res.rc
This adds msvc project files and tiny code changes,
required to build this project with msvc.
Microsoft resource compiler, unlike mingw's windres,
doesn't fully support macros and multi-line strings,
so I had to create a separate resource file for msvc.
> msvc: preliminary support

- openvpn.c
The current code re-issues the next read request from the I/O
completion routine before the previous message is fully handled.
This could potentially lead to lost messages as the message buffer
is reused.
Fix by re-queuing the next read from OnService() after duplicating
the previous message.
The length check of the read message is omitted as it is implicitly
checked when scanning the message. Makes the logic simpler.
Reported by Lev Stipakov <lstipakov@gmail.com>
> Re-queue reading from service only after previous message is handled

- res/openvpn-gui-res-de.rc
- res/openvpn-gui-res-en.rc
- synchronized the german resource files with the english version
- corrected hyphens that should have been En dashes
> Update English and German language files

- main.c
- misc.c
- misc.h
- openvpn.c
- options.c
- res/openvpn-gui.manifest
This pull request replaces PR #346. Provides per-monitor DPI scaling and replaces the old SHBrowseForFolder dialogs with modern IFileOpenDialog alternatives.
> Support per-monitor DPI scaling and modern filedialogs

- res/openvpn-gui-res-de.rc
- res/openvpn-gui-res-dk.rc
- res/openvpn-gui-res-en.rc
- res/openvpn-gui-res-es.rc
- res/openvpn-gui-res-fa.rc
- res/openvpn-gui-res-fi.rc
- res/openvpn-gui-res-fr.rc
- res/openvpn-gui-res-it.rc
- res/openvpn-gui-res-jp.rc
- res/openvpn-gui-res-kr.rc
- res/openvpn-gui-res-nl.rc
- res/openvpn-gui-res-no.rc
- res/openvpn-gui-res-pl.rc
- res/openvpn-gui-res-pt.rc
- res/openvpn-gui-res-ru.rc
- res/openvpn-gui-res-se.rc
- res/openvpn-gui-res-tr.rc
- res/openvpn-gui-res-ua.rc
- res/openvpn-gui-res-zh-hans.rc
- res/openvpn-gui-res-zh-hant.rc
Note: to be merged after PR #408 as --management_port_offset is included here.
Describe recently added command line options:
- iservice_admin
- disable_popup_messages
- popup_mute_interval
- management_port_offset
Added the default English text to all langauage files.
> Update help message

- res/openvpn-gui-res-pl.rc
- the style of the translation has been slightly improved,
- untranslated fields has been translated
> Update Polish translation in openvpn-gui-res-pl.rc

- tray.c
Trying again to get a better connecting checkmark --- this is meant to replace PR #406 which was not up to the mark. Looks better except for some ant-aliasing due to scaling.
The bitmap is recreated every time the popup menus are made although its sufficient to recreate it when system colours change. 
In fact we should reconsider the current practice of scanning config directories and recreating menus multiple times as its a slow process when there are 100's of configs. Left for later.
> Apply transparency mask to the connecting-state checkmark image

- openvpn.c
This is the same as commit 3 of #441, but issuing separately as this is a bugfix, has no Windows quirks, and could get a quick review .. wink-wink.
Fixes parsing of the challenge text that could contain the
delimiter ':'
> Bug fix for challenge string parsing

- as.c
- HTTP auth password appears to be cached and reused
unless replaced by a non-empty string. When user-supplied
password is empty, use some arbitrary string "x" as the
password.
- Make username required for generic URL as well.
- Also clear password buffers after use.
> Clear password used for profile import

- .github/workflows/msbuild.yml
> Github Actions: use Release build configuration

- main.c
- misc.c
- misc.h
- options.c
- options.h
- passphrase.c
- registry.c
> Load legacy provider when required

- misc.c
Fixing my own mistake in PR #483 
> Check pointer is not NULL before passing to strlen

- misc.c
Commit 6271d2f67 added escaping of single quote in
quoted strings which is wrong. Fix it.
Ref: issue #487
> Do not escape single quote character

- CMakePresets.json
> CMakePresets: fix arm64 debug/release config

- localization.c
- pkcs11.c
An improvement and a bugfix that were missed when PR #508 was merged.
> pkcs11-id-management fixup

- res/openvpn-gui-res-ru.rc
Some parts of interface haven't been translated, so I added the missing lines
> Add missing Russian localization lines

- README.rst
- openvpn.c
- Forget passwords while stopping persistent connections
- Update README
- Document persistent and PLAP in README
> forget-passwords on disconnect and README edits

- configure.ac
Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>
> Bump version to 11.31.0.0

- configure.ac
Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>
> Bump version to 11.32.0.0

- configure.ac
- echo.c
- localization.c
- localization.h
- main.c
- openvpn.c
- options.c
- plap/plap_connection.c
- plap/ui_glue.c
This also bumps lowest supported Windows version to Windows 7 in mingw builds. I'm not sure what we target in MSVC.
> Make popup message boxes RTL language aware

- openvpn.c
WEB_AUTH is treated same way as OPEN_URL with no support for optional flags in WEB_AUTH message. In particular, proxy is not supported.
Closes #414
> Add support for WEB_AUTH requests from server

- res/openvpn-gui-res-it.rc
Complete italian translation
Use the feedback posted in PR 510.
I hope that I made all changes requested in PR 510.
> Update italian language

- Makefile.am
- plap/Makefile.am
Fixes #585
Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>
> Makefile.am: Fix dist* targets to include all required files

- main.c
- openvpn_config.c
- pkcs11.c
- tray.c
This completes all "bugs" I found while looking for what causes #577. None of these would explain the crash in #577 though. I also have a fix for #576, but it requires more testing. For lack of time, leaving it for 2.6.1.
> Misc fixes

- localization.c
- localization.h
- main.c
- main.h
- manage.c
- misc.c
- misc.h
- openvpn.c
- options.c
- pkcs11.c
- plap/plap_connection.c
- plap/ui_glue.c
- proxy.c
- scripts.c
- tray.c
- tray.h
Fix for #576 and some related changes.
> Dialog owner, replacement for Sleep etc.

- CHANGES.rst
- main.c
> Fix --command disconnect_all

- CHANGES.rst
To be merged with version update to 11.39
> Update CHANGES.rst for 11.39.0

- BUILD.rst
> BUILD.rst updates

- config-msvc.h.in
- openvpn.c
Current IV_GUI_VER is always 11 which is not very helpful.
> Send the whole version in IV_GUI_VER

- qr.c
Add a timer to periodically call SetThreadExecutionState and simulate mouse movement using SendInput, preventing the pre-logon UI from being dismissed due to inactivity during mobile QR code authentication.
> Keep PLAP dialog alive by simulating user activity
