nsis/openvpn-gui.nsi
registry.c

Openvpn no longer terminates but restarts on suspend. This conflicts with
the stop/restart logic in the gui during windows power state change events.
This patch changes the default behaviour so that SIGTERM is not triggered
during windows suspend.

Do not disconnect on suspend

---

res/openvpn-gui-res-ru.rc

The first line of the page is too long for the current width, so it spills onto the second line, shifting the rest of the text downwards. As a result, the line with the URL is shifted out of the label's bounds and is no longer visible.

Widen the Russian About page

---

localization.c

$ cppcheck .
Checking localization.c...
[localization.c:224]: (error) va_list 'args' was opened but not closed by va_end().

fix cppcheck warning

---

res/openvpn-gui.manifest

Request the highest privilege of the invoking user. When started by a
user with admin rights, a UAC prompt may pop up requesting consent.
The current behaviour is preserved for users with limited privileges.

Run with highest privilege available

---

openvpn.c

This is needed to avoid early messages going to stdout leaving no
trace of errors when openvpn exits before management interface is up.
It also ensures that any --log directives in the config do not override
the log file location.

Put --log first in the command line

---

main.c
manage.c
openvpn-gui-res.h
openvpn.c
openvpn_config.c
options.h
res/openvpn-gui-res-en.rc
service.c

- Handle early errors (openvpn exits before management connection is up)
with a helpful error message that points the user to view log.
- Include only readable config files in the connection list
- Warn if no connection profiles found
TODO: handle startup errors from interactive service

Better error reporting when connection fails to come up

---

res/openvpn-gui.manifest

This reverts commit 2af86368964a55c662a2f8548f363e2d65fcbb94.
Requiring "highestAvalable" privilege is no longer required,
nor advisable, as the same functionality is provided using
the interactive service with the GUI running with limited rights.

Revert "Run with highest privilege available"

---

misc.c
misc.h
openvpn.c

two commits from master
1. IsAdministrator() check needed for security -- see the commit message
2. Put log first: useful in general as it avoids empty log after errors -- see also [#567](https://community.openvpn.net/openvpn/ticket/567)

Cherry picked for release/10

---

main.c
openvpn_config.c
options.h
registry.c
res/openvpn-gui-res-en.rc
service.h

Collect configs from both locations so that existing installations may not be adversely affected while new users can install configs in their user profile. As a side effect, makes PR#17 work for non-admin users.
- Set default config directory (config_dir) to %UserProfile%\OpenVPN\config
(saved and read back from HKCU\Software\OpenVPN-GUI\config_dir)
- Add a global_config_dir variable read from HKLM\Software\OpenVPN\config_dir
or set to OpenVPN-install-path\config
- Scan both directories and their sub directories for connection profiles.
In case of name conflicts config_dir gets priority over global_config_dir
- Eliminate multiple warnings of duplicate configs

Support user and global config directories

---

main.c

found by cppcheck.
Before this fix, `o.auto_connect[i]` will be evaluated before `i < MAX_CONFIGS`.

Fix potential out-of-bounds access

---

Makefile.am
access.c
access.h
main.c
main.h
misc.c
misc.h
openvpn-gui-res.h
openvpn.c
options.c
options.h
registry.c
res/openvpn-gui-res-en.rc
service.c

This is not fully ready for a pull request but I need some feedback. So here goes:
It includes #PR18 as the first commit as without that the rest doesn't make much sense -- so ignore that commit
The second commit adds some functionality to check whether a config will be treated as authorized by the interactive service. If not it offers and option to add the user to the "OpenVPN Administrators" group (or its equivalent). Is this a good idea? If it fails to add the user to this group should we start the connection without using the service (i.e default to the old behavior)? Note that such an action may be useful for some connections that could be established without admin rights.
This is supposed to be tested with the latest openvpn git master and the HKLM registry keys required for the …

handle iservice policy restrictions

---

.gitignore
Makefile.am

When using `make maintainer-clean` the file `compile` was not removed.

File 'compile' now removed as well

---

manage.c
manage.h
openvpn.c
openvpn.h
options.h

To test, try to trigger an option error or an auth error using, say, config in user profile 
as a limited user, not member of ovpn_admin_group. Interactive service must be running.
This is against the current master, may not cleanly apply on top of PR#26

Read errors from the service pipe and handle fatal ones

---

openvpn_config.c
tray.c

The first patch is a minor bug fix -- add a missing call to CheckReadAccess() and also simplify its usage.
The second patch adds a feature that helps the "import file" option:
Currently if a config is imported when connections are active it does not appear in the config list until all connections terminate or GUI restarts. The patch makes it possible to rescan for configs even if connections are active.

Rescan configs

---

.travis.yml

```
(*) cache openssl download when compiling in Travis CI
(*) stop compilation on every warning
```

cache openssl download

---

res/openvpn-gui-res-en.rc

No new line for "Starting this connection requires membership in"

---

openvpn_config.c
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc

The popup message shown when no config files are present now includes a pointer to the "Import File.." menu and the location of the user and global config directories.
Note: Translations of the added text is missing.

Improve the message shown when no config files are found

---

main.c
openvpn.c
options.h

This makes it less confusing to run GUI v11 with OpenVPN 2.3.x

Check for interactive service only if OpenVPN version is >= 2.4

---

openvpn.c

WINAPI is __stdcall in 32 bit windows (ignored in 64 bit) causing
this bug to show up in the 32 bit version only.
Also fix out-of-bounds write of ovpn_version[] in openvpn.c
Resolves Trac #758

Add missing WINAPI in the definition of HandleServiceIO

---

main.c
main.h
openvpn.c
options.h
res/openvpn-gui.manifest

- Set dpi-awareness to true in the manifest (i.e., "system-dpi aware")
- Check system dpi and scale and/or position widgets and windows
that depend on the system dpi (only components within the status
window are affected).
Note: Declaring dpi awareness eliminates automatic rescaling of
windows that causes blurred text on high dpi monitors.
Windows 8.1 and later allow per monitor dpi setting which is
not handled here.

Make the program DPI aware

---

localization.c
localization.h
openvpn.c
tray.c

- Check system metric for large and small icon sizes and
try to load the correct size instaed of scaling from one size.
Scaling will still happen if the required size is not available
in the icon resource. As we add more icon sizes they will
get automatically used as needed.
LoadImage scales up from next smallest size available. Revisit this
when LoadIconWithScaleDown (Vista+) becomes available in mingw.
Resolves Trac: #772 (icon scaling issue)

Load icons at sizes given by DPI-dependent system metric

---

README.rst
main.c
openvpn.c
openvpn_config.c
res/openvpn-gui-res-en.rc

Two commits:
1. Distinguish between state change messages: CONNECTED,SUCCESS and CONNECTED,ERROR -- this avoids wrongly reporting incomplete connections as successful (see e.g., https://www.mail-archive.com/openvpn-users@lists.sourceforge.net/msg03437.html where setting ip address failed but GUI reported success). 
Note: OpenVPN reports connections completed with route setting errors  as "CONNECTED,SUCCESS", so such cases will continue to be treated as success by the GUI.
2. Disable warning popups (such as interactive service not running  or duplicate configs found) when silent_connection is true. (As discussed under issue #111).

Some error reporting improvements

---

configure.ac
main.c

Some related infos:
* https://github.com/rust-lang/rust/issues/16514
* https://sourceware.org/ml/binutils/2014-08/msg00177.html

Enable ASLR & DEP

---

configure.ac

The change will help warn against use of API calls not in vista.
The original setting of this macro to  _NTDDI_WINXP was wrong and
permitted use of any API not just those supported by WinXP. Build
is unaffected as we currently do not have any function calls not
present in Vista.

Update _WIN32_WINNT to _WIN32_WINNT_VISTA

---

Makefile.am

The openvpn-gui-res-cs.rc file was not included in release tarballs, which made
tarball-based builds fail.
URL: https://github.com/OpenVPN/openvpn-gui/issues/131

Fix builds from release tarballs

---

appveyor.sh
appveyor.yml

AppVeyor stores artifacts, it might be used for "test new feature" builds.
also, it is useful to build in cygwin regularly
@mattock , can you add openvpn-gui to ci.appveyor.com ?

AppVeyor support

---

localization.c
localization.h
main.h
options.c

- Increase the buffer size used to load the usage string to 2048
chars (defined by USAGE_BUF_SIZE in main.h)
- Make GetGUILanguage() visible outside localization.c
Trac: #833

Fix truncation of usage message shown when --help is used

---

access.c
openvpn.c
res/openvpn-gui-res-en.rc

(updated)
See also [Trac #810](https://community.openvpn.net/openvpn/ticket/810)
~Compare the SID of the user with member SIDs in the Administrators
group and ovpn_admin_group. This avoid issues on setups where the
DC may not be reachable and allows validating users logged in with
cached credentials.~
Authorize the user if
(i) admin groups are found in the process token
(ii) or the SID of the user is a member of the admin groups
The second check is needed to support adding the user to the
ovpn_admin_group when GUI is running, as such changes in group
membership will not be reflected in the token.
Same approach is used in the proposed patch (v2) for interactive service
http://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg13834.html

Check group membership without needing connection to DC

---

README.rst
main.c
openvpn.c
openvpn.h
openvpn_config.c
options.c
options.h
registry.c

Issue #105
- A new registry HKLM\Software\OpenVPN\disable_save_passwords
(32 bit DWORD value) may be set to a non-zero value to
disable password saving by users. Applies to both auth and
private key passwords. Usernames are always saved.

Add a system-wide option to disable the password save feature

---

appveyor.yml

it turned out that reinstalling mingw-gcc-core lead us to strange cygwin behaviour, gcc became ununsable (even "$CC --version" failed), so .. I decided to not install those compilers

AppVeyor: switch to preinstalled mingw64-%ARCH%-gcc-core

---

main.c
manage.c
openvpn.c
openvpn.h

Support the following echo commands
- "echo forget-passwords": delete passwords internally saved by the GUI
but do not disable the password save feature. Useful when pushed
from the server so that it gets processed after authentication. Also see
management-notes.txt in openvpn docs.
- "echo save-passwords": enables private-key and auth-user-pass passwords
to be saved. Will be effective at startup only if present in the config
file. If pushed from the server, will get used for subsequent
password prompts. Essentially this has the effect of presenting the password
dialogs to the user with save-password checkbox selected. The user may still
uncheck it during the dialog.
Note: echo commands are processed as and when they are received and in the order
received.
TODO: support "echo setenv", …

Parse ECHO directives from openvpn

---

openvpn.c

When the username is filled automatically, set the focus to the password field. This way you can enter the password immediately without having the press TAB (or even worst users using the mouse to click on the password field).

Set focus to password field when username is filled

---

.appveyor.yml

APPVEYOR_PROJECT_SLUG point to project path properly, when
repo is cloned, deleted and cloned again

AppVeyor: use proper way to resolve project path

---

manage.c
misc.c
misc.h
openvpn-gui-res.h
openvpn.c
res/openvpn-gui-res-en.rc

A very basic validation of user input (username/password, private key passphrase) to avoid errors in communication over the management socket. The patch only disallows embedded '\n', but more exclusions could be easily added as necessary.
Invalid input shows an error-tip as in image below:
Commits:
1. An error in parsing of process ID received from the service is corrected
2. Input validation
3. Define a macro used in previous commit missing in some mingw versions --- could be avoided by updating CI builds to use a newer mingw (say ubuntu 16.04)
~~Tested by: @Handle (Trac #958)~~
Tested by: @H4ndl3  (Trac #958)

Validate user input

---

registry.c

Allow the GUI to run without any registry keys present:
the location of openvpn installation defaults to
C:\Program Files\OpenVPN if not found in registry.
Useful for testing builds or to display --help etc.
See also: PR #147

Add a default for openvpnpath

---

res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-ua.rc
res/openvpn-gui-res-zh-hant.rc

@selvanair , was "74" specified in purpose ?
if not, "80" seem to be better
74:
80:

better alignment of warning message

---

openvpn.c

Without this, after an auth-failure, the next password prompt could cause an automated submission of an empty password unless the user interrupts.
- This case was missed by commit 5fb23f6ad9 that introduced automatic username/password submission

Do not auto submit username/password after an auth failure

---

openvpn.c

- As disable_save_passwords may be enforced system-wide by an Administrator,
"echo save-passwords" should not be allowed to over-ride it. This was
overlooked in commit d4090a8842990ba992d843c49eaec1760ac03b0e.
Fix it by ignoring this echo directive if disable_save_passwords is in
effect. Also write a log message to the status window.

Do not allow "echo save-passwords" to override disable_save_passwords

---

openvpn.c
res/openvpn-gui-res-en.rc

After a failure the auth-pass dialog is shown with the password
field prefilled but highlighted. This allows the user to easily
overwrite the password or resubmit the old password if the
failure was temporary.
After a private key passphrase failure, the dialog is not
prefilled with saved password as this failure happens locally
and in such cases the password is very likely wrong.
If the user aborts the dialog by pressing cancel, the saved
password will get used during the next connection attempt.
Wrong username or password warning text is changed to: "Wrong
credentials".
See also issues: #227 #217

Do not clear saved passwords on verification failure

---

registry.c

- When registry keys were simplified, the log viewer and editor
entries were removed in favour of file associations that the
user can independently control.
Yet, there are times when an associated application fails to start
or no associations are present etc., and its useful to have a fall
back editor setting to open .ovpn and .log files.
This patch sets that default as "notepad.exe"
- Also remove the unused profile_dir[] in registry.c

Set a fall back for editor if file association fails

---

main.c
main.h
misc.c
misc.h
options.c
options.h

When openvpn is run with --help option it pops up a help
message and exits when that window is closed. Such instances
cannot accept any commands and should not be treated as a
running instance.
Fixes issue: #237
Additionally log errors to the event log when sending a command to a 
running instance fails. This supplements the non-zero exit-code
set in such cases.

Fix detection of an already running instance

---

openvpn.c

When using interactive service, route addition should use the
service. The user may not have privileges to set routes
otherwise.  We already override any --route-method set in the
config file as openvpn.exe is started with --msg-channel as the
last option which sets route-method to ROUTE_METHOD_SERVICE.
This patch extends that to pushed --route-method
Also change _T("") to L"" in the edited lines to be explicit about
wide and narrow strings. We no longer support non-unicode builds.
No change when interactive service is not used.
Ref: issue #281

Ignore pushed --route-method when interactive service is in use

---

configure.ac
main.c
main.h
openvpn_config.c
options.c
options.h
registry.c
tray.c
tray.h

By default, enabled only when number of configs > 50 but can be forced using `--config_menu_view 2` on command line. TODO: make this configurable from the settings menu
As an example the following directory structure 
CUSTOMERS/agony/dreamcity/dreamcity.ovpn
CUSTOMERS/agony/boonies/boonies.ovpn
CUSTOMERS/woeful/woeful-gw/woeful-gw.ovpn
PROVIDERS/dont-trust/washington/washington.ovpn
PROVIDERS/dont-trust/london/london.ovpn
PROVIDERS/broken-cipher/bypass-netflix/bypass-netflix.ovpn
WORK/scinet/scinet.ovpn
sample.ovpn
broken/broken.ovpn
Displays as
CUSTOMERS> agony>  dreamcity> connect,disconnect
boonies>   connect...
woeful> woeful-gw> connect...
PROVIDERS> dont-trust>    washington>     connect...
london>         connect...
broken-cipher> bypass-netflix> connect...
WORK> scinet> connect... …

Implement a nested menu for configs in subdirectories

---

localization.c

When a resource is not found in user's preferred language, first
try the primary language with SUBLANG set to default before
falling back to English.
See issue #216

Fallback to default sublanguage when loading resources

---

misc.c
misc.h
openvpn.c

Parent keeping the handle to write end of child's stdout will
cause ERROR_BROKEN_PIPE not signalled if/when the child exits.
Also add a wrapper for CloseHandle()
Fixes the GUI process hanging in read from child
if the latter unexpectedly dies due to some error.
Trac #1203

Promptly close pipe handles passed to child

---

res/openvpn-gui-res-fi.rc

res/openvpn-gui-res-fi.rc: add missing IDS_MENU_RECONNECT translation

---

misc.c

By default CryptBinaryToString used for base64 encoding
adds CRLF every 76 characters or so. As LF is used as
the message delimiter by the management interface, this breaks
handling of static challenge.
Fix by setting CRYPT_STRING_NOCRLF in the flags. With this
change, the trailing '\r\n' removal is no longer required.
Fixes Issue 317: https://github.com/OpenVPN/openvpn-gui/issues/317

Do not add CRLF to base64 encoded output

---

README.rst
main.c
main.h
options.c
tray.c

Add an new command 'rescan' that may be sent to a running
instance of the GUI to force it rescan the config folders.
Use case: with an instance of the is GUI running, one can
manually copy a config file to the config folder and start
it using "openvpn-gui --command rescan" followed by
"openvpn-gui --command connect foo"
v2: The calls to rebuild config file list and recreate
menus is refactored into a function.
See also: #319

Add '--command rescan' to rescan config folders

---

registry.c

Also if install_path read from registry is an empty string, illegal
memory access may result. Fix by using the default value in this
case as well.

Fix ReadRegValue when data read from a registry key is of zero length

---

main.c
openvpn-gui-res.h
res/openvpn-gui-res-en-msvc.rc
res/openvpn-gui-res-en.rc

- Prompt the user for permission if import may overwrite
an existing config.
- Also raise an error if the import file source matches the
global or local config directory. Reimporting a config on to
itself is not supported. This also  avoids ERROR_SHARING_VIOLATION
in CopyFile() when source and destination are the same.

Optionally allow overwrite when importing a config

---

res/openvpn-gui-res-it.rc

See also Trac #1265 https://community.openvpn.net/openvpn/ticket/1265
Fixed dialog images are below:

Fix text truncation in the settings menu for Italian translations

---

misc.c

Strings passed to the management interface should escape characters
such as " and \ that have special meaning for the parser.
But, static-challenge password and response are base64 encoded
before passing to the management interface and get literally
transported to the server in that form. Escape processing of
these strings could result in altering the password and/or response.
Reported by: macskas https://github.com/OpenVPN/openvpn-gui/issues/351

Do not do escape processing on static-challenge password and response

---

res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-zh-hans.rc
res/openvpn-gui-res-zh-hant.rc

- All missing strings are copied from the English version
which is the default.
- Description of "--command cmd" is also copied from the
English version where missing.
- Some white-space changes for consistent formatting of all files
No user-visible changes except for the --help output
which will now include a description of the "--command cmd"
option in English when a translation is not available.

Copy missing resource strings to all language files

---

main.h

The help message is truncated in some languages with
recent increases in textual information in the
usage string. Eg., see "openvpn-gui --help" with
Dutch selected as the language where the text
is about 2300 characters while the buffer is only 2048.
The window still fits on typical screen sizes, so
just increase the buffer size to 3000.

Increase the buffer size for help message

---

res/openvpn-gui-res-nl.rc

This PR adds three missing Dutch translations (`IDS_NFO_IMPORT_OVERWRITE`, `IDS_ERR_IMPORT_SOURCE` and `IDS_NFO_BYTECOUNT` and modifies the text in the `ID_DLG_ABOUT` dialog to match the English source text.
I have also aligned the order of the lines in the file and some whitespace with the `openvpn-gui-res-en.rc` file to make file comparison easier.

Add missing Dutch translations, align with en resource file

---

openvpn_config.c

Some users want to use more deeply nested folders than currently
supported. Increase the max depth to 20 which should be plenty for
all.
See also issue: #364

Increase the depth of directories scanned for config files

---

localization.c
main.c
openvpn-gui-res.h
openvpn.c
options.c
options.h
registry.c
res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-en-msvc.rc
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-ua.rc
res/openvpn-gui-res-zh-hans.rc
res/openvpn-gui-res-zh-hant.rc
service.c

We didn't use interactive service when gui was running
under admin because of some privilege escalation vulnerability in Vista.
Apparently this issue doesn't exist on Win7 and newer versions so
it is safe to use iservice on those systems.
Introduce "Always use interactive service" option,
which is "on" by default. This should enable users,
who by various reasons run gui as admin, use Wintun.
When gui is running as admin and interactive service
cannot be started or not installed, warn that wintun will not work.

Introduce "Always use interactive service" option

---

scripts.c

This PR puts the output of the connect script `connection_up.bat` to a logfile named `connection_up.log` next to the other logs.
For now I only implemented this in the connect script, but obviously this needs to be done for the preconnect and disconnect script. I will add that code once the code I pushed so far is reviewed.

Put the output of the connect script to a log file

---

openvpn.c

As discussed in #177 a fix to only change the state to reconnecting when already connected
Fixes #177

Only change to reconnecting when already connected

---

openvpn.c
tray.c

Currently we pop up the status window on double click only
if one connection is active though there is no strong reason to
limit this behaviour. In fact, when multiple connections are
stuck in the connecting state, its very useful to have a quick
way to examine their progress instead of having to drill down
the menu. Especially so when nested menu is in use.
A random variation of up to 100 pixel is added to the initial
position of the status window to avoid all windows falling on
top of each other.
To prevent an explosion of new windows in the very unlikely event
of numerous active connections, restrict the maximum windows
shown to 10.
Also see discussion under #372

Open all active status windows on left-double-click

---

localization.c
localization.h
tray.c

Currently we show a check mark on connected profiles with no
indication on profiles that may be in the connecting state.
Change this by adding a mark against connecting/reconnecting
profiles. The yellow connecting state icon is used to generate
this mark although a custom designed check mark may look better. 
In case of nested configs, the parent menus are marked with a tick
mark and only the profile is marked with the connecting icon.
Eg., here is one connected and one connecting profile each.
No change in behaviour for profiles that are connected or
disconnected.
Trac #1241

Show a mark against profiles that are in connecting state

---

Makefile.am

Lack of this caused official release builds to fail:
```
res/openvpn-gui-res.rc:50:10: fatal error: openvpn-gui-res-fa.rc: No such file or directory
#include "openvpn-gui-res-fa.rc"
^~~~~~~~~~~~~~~~~~~~~~~
```

Add Farsi language package to tarballs

---

openvpn_config.c

Extend the string comparison of the two paths to include comparing their
file information structure.  (See Remarks under the MSDN docs for
GetFileInformationByHandle)
If the strings are identical we treat them as identical without checking
further whether the paths are valid. This matches the current
behaviour (except that we do a case-independent comparison). Otherwise, 
the two paths are treated as identical if both exist, are accessible and 
point to the same object in the file system.
Trac: #1359, #1376

Improve the check for whether global and local config_dir are the same

---

openvpn.c

- In User-Auth dialog require non-empty password or PIN
- In generic password dialogs require non-empty inputs
- Fix handling of dynamic challenge when response is not required
Issue: #417

Do not allow empty password input

---

passphrase.c

Use an empty password to clear any existing password in the
private key file. If not empty, the requirement of minimum 8
characters is retained.
For PEM key file, an empty password will clear encryption on
the key. For pkcs12 files it will set an empty password.
As use of an empty password is the default first try in
OpenVPN.exe when reading pkcs12 file, this effectively leads
to the user not prompted for a private key password during
connection setup.
See #422

Allow clearing of key password in ChangePassphraseDialogFunc

---

openvpn-gui-res.h
res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fa.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-ua.rc
res/openvpn-gui-res-zh-hans.rc
res/openvpn-gui-res-zh-hant.rc

Should fix duplicate control id warnings from resource
compiler.

Have unique and non-zero IDs for all controls

---

res/openvpn-gui-res-es.rc

This is rebased on top of PR #425 -- so ignore commit 1
Fixes: ..\openvpn-gui\res\openvpn-gui-res-es.rc(219): warning RC4206: title string too long; truncated at 256

Text truncated in spanish translation: fix by removing repeated phrase

---

openvpn.c

As with CRV1, submit an empty string as the response.
Our base64-encode functiton can handle empty input to generate
an empty string as output.
Also make ensure the message box is shown in foreground,
and not dependent on the status window which may be hidden.

Handling of CR_TEXT when no response is required

---

main.h
openvpn.c

- All windows are notified when OpenVPN state changes -- cr-text dialog is made to close on receiving this (see issue #440)
- Change the way "challenges" that require no response are processed -- required to handle state-change notification
- Fix a bug in the parsing of the challenge text (we were truncating strings that contain colons)

Close cr-text challenge dialog on state change

---

README.rst
main.c
misc.c
openvpn-gui-res.h
options.c
res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fa.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-ua.rc
res/openvpn-gui-res-zh-hans.rc
res/openvpn-gui-res-zh-hant.rc

Add a command-line option
`--command import full-path-of-config` 
(alternatively `--import full-path` also works)
Could be called from a second instance or first instance.
Rationale: `openvpn-gui.exe --command import path` could be used to import a downloaded config. Setting this as the default command for `.ovpn` files would make easy import by double click, right click and choose default action or even automatically with some browser co-operation. 
TODO: set this command as the default shell action during installation.

Import command

---

as.c
misc.c
misc.h

As suggested in #450, parse Content-disposition: header for filename. If not found fallback to parsing the file content for metadata as before. In case of import from AS, no change.
May be tested using the following URLs in the "Import from URL" dialog:
(i) https://webhost1.sansel.ca/zbcm_4Lin4hyxkknkOLqWgdkWAf7mOmv/test-8859.php
(ii)https://webhost1.sansel.ca/zbcm_4Lin4hyxkknkOLqWgdkWAf7mOmv/test-utf8.php
The first one sets `filename="test-8859-with-e-acute-é.conf"` with an iso-8859 e-acute character in name, (ii) sets `filename*=utf-8''test-utf8-with-e-acute-é.conf` in addition encoded as utf8. The parser should pick the utf-8 name in the latter case. Note that the extension in the file name is replaced by whatever extension is in effect in the GUI (".ovpn" by default) during import. …

Import URL: some enhancements

---

misc.c
tray.c
tray.h

When clicking on tray icon, menu items are deleted and then recreated.
Deletion uses o.num_config:
for (i = 0; i < o.num_configs; i++)
DestroyMenu(hMenuConn[i]);
Commit 8e4183f9 ("Add '--command import' command line option")
added BuildFileList() call which modifies o.num_configs
but doesn't touch menus. When clicking on tray icon after import,
abovementioned code attemps to access invalid item in hMenuConn array
and crashes when this is the first imported profile and hMenuConn is NULL.
In other DestryMenu is called with invalid argument.
Fix by recreating popup menus instead of just rescan file list -
this will first delete menus with correct o.num_config value.

Fix crash when clicking on tray icon after importing the first profile

---

passphrase.c

When we link with natively-built OpenSSL .DLLs
(not cross compiled with MinGW), we are expected to include
applink.c, which provides glue between OpenSSL BIO layer
and compiler run-time. This doesn't apply to ARM64.
Failure to do that results in "no OPENSSL_Applink" fatal error
during password change.
See the corresponding fix in openvpn2:
https://sourceforge.net/p/openvpn/mailman/message/37361982/

Fix broken "change password" functionality

---

as.c
main.c
misc.c
misc.h
openvpn-gui-res.h
res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fa.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-ua.rc
res/openvpn-gui-res-zh-hans.rc
res/openvpn-gui-res-zh-hant.rc

The user is prompted with a message showing the config
name that will be imported. The user can accept or cancel
the operation.
If the user was already prompted for over-write permission
because a config with the same name exists, no further dialog
is shown.
Import using the menu (Import File...) is not affected.
Rationale:
We want to set "Import" as the default verb for the context
menu of .ovpn files. This will allow import of configs by
double-click. Also when .ovpn file is downloaded using a browser,
setting the default browser action to "open" will result in an import.
In such cases a silent import action could be surprising, and a
prompt showing what is being imported could provide a better UX.
On the flip-side, the prompt/dialog will also be shown when import
is done from the …

Show a prompt during profile import using --import

---

.github/workflows/msbuild.yml
CMakeLists.txt
vcpkg.json

Add openssl3 support for msvc build
- remove vcpkg manifest and use whatever openssl
version is installed. To build with openssl3, one could
use openssl3 port from openvpn/contrib/vcpkg-ports.
- build with openssl1.1.1 and openssl3 in GitHub Actions

Add openssl3 support for msvc build

---

misc.c
misc.h
openvpn.c

Escape the username string before passing to management
interface. For other dialogs this is already done.
Move string-escape to a function and process the username
through it.
Also escape space, single quote in addition to double quote
and backslash.
Reported by: Jakob Curdes <jc@info-systems.de>
Issue: #482

Fix passing username for CRV1 response

---

CMakePresets.json

Sadly, CMake/Ninja combo doesn't work well for ARM64
(similar to
https://stackoverflow.com/questions/47581784/building-a-x86-application-with-cmake-ninja-and-clang-on-x64-windows)
- it silently produces x64 binaries instead of arm64.
Switch to slower MSVC generator.

CMakePresets.json: use MSVC generator for ARM64 builds

---

CMakePresets.json

Ninja makes build slightly faster but requires running
"x64" developer command prompt, not the "default" one.
Without that, cmake silenly produces x86 binaries and it might
take a while to find out the reason. To avoid confusion, switch back
to MSVC generator.

cmake: replace Ninja generator with MSVC

---

main.c
manage.c
manage.h
openvpn.c
openvpn.h
options.h

In  some cases the service may take a while to startup openvpn.exe,
causing connection to the management interface to timeout. This could
leave  behind the OpenVPN process if/when it eventually starts up.
(Trac 905, 1050).
As errors in starting up the OpenVPN daemon are independently
handled, its better to keep retrying the management interface connection
until aborted due to errors or by the user.
- On timeout, log a message on the status window and retry the
management interface connection
- Eliminate the timed-out state that is no longer used
- Call StopOpenVPN() before abort so that OpenVPN daemon
is not left running in case it starts up later.
- In the unlikely event that OpenManagement() fails, show an error
- User can abort by pressing disconnect
A "retrying.." message is logged on …

Retry on management timeout instead of aborting

---

misc.c
misc.h
openvpn.c

Bind a socket to a dynamic port and then close to identify
a free port and use it when starting openvpn.exe.
Trac: 1051

Automatically choose management interface port number

---

openvpn.c

OpenVPN3 doesn't yet support "state"
management command without parameters.
While this has to be fixed on OpenVPN3
side, it doesn't mean that gui could simply crash.

Fix crash on empty state response

---

main.c
service.c
service.h

CheckServiceStatus() return value is never used - the status is set to global options_t struct.
While on it, remove unneccessary "false" argument
and reformat the code.

service: change CheckServiceStatus() return type to VOID

---

README.rst

- Download link was outdated.
- Link to docs on configuration pointed to the main page of OpenVPN Inc.
which is hardly helpful -- point to the configuration section of the
HOW TO instead.

Update links in README.rst

---

openvpn_config.c
options.h
tray.c

Since version 11.30, we scan config-auto folder and show them
in the menu of available connection profiles. To reduce user-confusion,
always group these configs under a sub-menu ("Persistent Connections")
even when nested config menu view is not in use.

Connection grouping improvements

---

openvpn.c
options.h

As we now allow users to set a management password (for persistent connections), the max size of password should match what openvpn.exe can handle (128 or 4096 bytes depending on build options).
Increase the buffer size to 4096 though such large passwords may not work in practice. 127 bytes + NUL, may be a safe upper limit.
For the random password used for connections spawned by the GUI, the current size of 15 bytes + NUL is retained.
Fixes: #567

Increase max size of management password buffer

---

.github/workflows/msbuild.yml
BUILD.rst

This will bump OpenSSL version to 3.0.7, the same
we use for master and release/2.6.

Update vcpkg commit id

---

CHANGES.rst
openvpn-gui-res.h
openvpn.c
res/openvpn-gui-res-en.rc

OpenVPN 2.6 now reports `CONNECTED,ROUTE_ERROR` when connection completed. Currently in the GUI we will treat this as an error and may be seen as a regression by some users.
Until we decide on how to treat route errors in the GUI, this PR is a quick fix to handle it almost the same way as the _status quo_. What is added is some extra error logging and automatic popup of the status window to draw attention to the errors.
**Change in behaviour when using 2.6 master:**
If openvpn.exe reports CONNECTED,SUCCESS or CONNECTED,ERROR: no changes
If openvpn.exe reports CONNECTED,ROUTE_ERROR : 
- an error is written to the status log (in red)
- the status window is displayed (if not already open)
- the status window icon stays yellow
- the status text says "Connected with route errors"
- the tray …

Handle CONNECTED,ROUTE_ERROR from openvpn.exe

---

openvpn.c

- GetTickcount() and current-time passed-in to the callback are both 32 bit which wraps around every ~50 days. In the stop condition compare the elasped ticks and timeout value instead of end-time and now. The latter can wraparound in a long-running process.

Bugfix AutoCloseHandler(): accommodate wraparound of 32 bit time

---

main.c
openvpn.c
openvpn_config.c
options.c
options.h
plap/stub.c
plap/ui_glue.c
tray.c
tray.h
viewlog.c
viewlog.h

Currently we use an array of connection pointers which needs
to be reallocated when space runs out. But, that happens from
the main thread while the status thread may be referring to those
pointers. This can cause invalid memory access in some situations:
e.g., a connection is active and user adds tens of configs 
requiring a re-alloc during next re-scan.
Use a list instead of an array  so that connection pointer never
changes once created.

Bug-fix: Connection list

---

tray.c

To get connection for menu command, we use "dwMenuData" property of a menu. With single connection profile we read "dwMenuData" of a main menu, not a submenu. There has been a bug in code which hasn't set "dwMenuData" for the main menu but it has worked until recently, since this property stored index of connection array and index 0 has always worked.
Since commit 94179911 ("Use a list instead of array for connections list") we have switched to a linked list and store list pointer in dwMenuData. However due to bug dwMenuData has always being 0, and logic which fetches connections doesn't work:
minfo.fMask = MIM_MENUDATA;
GetMenuInfo((HMENU) lParam, &minfo);
c  = (connection_t *) minfo.dwMenuData;
if (!c)
break; /* ignore invalid connection */
Fix by assigning main menu's dwMenuData to a …

Fix broken menu functionality with single profile

---

manage.c

Commit 2b1e5867
"Replace Sleep by a Wait function that pumps messages"
replaced Sleep() with a wait function which also processes messages. However WM_MANAGEMENT message in some cases requires actual delay to be processed. To acheve that, filter out WM_MANAGEMENT from message dispatching.
Fixes https://github.com/OpenVPN/openvpn-gui/issues/619

Bring back delay before management is ready

---

res/openvpn-gui-res-en.rc

Configuration files located in `config-auto` require a management parameter to be declared. I added an additional line of detail in the error message to this effect. This error has historically caused confusion, and this additional messaging will clarify the fact that a management interface is _required_ to resolve the error.

Add clarity for error on missing management paramater.

---

openvpn.c

The tray icon and its tip text get updated to the connecting state when starting a new status window thread. This is not enough for persistent connections as these can be restarted from the hold state which does not go through a new thread creation.
To see the bug, disconnect and reconnect a persistent connection and have it wait in the connecting state. The tray icon colour does not change to yellow and the tray tip message does not show the "Connecting to:" text.
Fix by ensuring that  CheckAndSetTrayIcon() or SetTrayIcon() gets called whenever a state change message is received.
Fixes issue #668

Always update tray icon on state change

---

tray.c

Built-in tray notification icon has a tip text length limit of 128 characters which is often limited for showing the connected profile name, connected since time and IP addresses. If the profile name is long the IP numbers could get truncated.
Fix by using a custom tooltip window and display it when mouse hovers over the icon. As the status bar need not be at the bottom of the screen (could be at right, left or top as well), the location of the window is chosen based on the mouse co-ordinates that trigger the hover event.
In case of errors while setting up the tooltip window, fall back to the current behaviour.
If the message is too long to include time and IP, truncate the profile name part of the message.
Fixes issue #666
Edit: force pushed after fixing some typos in commit message and …

Use a custom tooltip window for the tray icon

---

.github/workflows/msbuild.yml

This adds a suffix _release or _asan to the zip file name in place of _Object.

Rename artifacts to avoid overwrite

---

openvpn.c
service.c
service.h

If an attacker with SeImeprsonatePrivilege manages to create a namedpipe server with a name matching that used by the "Interactive Service", the GUI connecting to it could allow the attacker to impersonate the GUI user.
Fix by validating the service pipe by comparing the pid of the pipe server with that of the "Interactive Service".
Note: GetNamedPipeServerProcessId() returns the pid of the process that created the first instance of the pipe. So, this patch only guards against a rogue pipe instance created before the service has started. This has to work in combination with a patch for the service that disallows creation of additional pipe instances when the service is running.
CVE: CVE-2024-4877
Reported by: Zeze with TeamT5 <zeze7w@gmail.com>
Acked-by: Lev Stipakov <lstipakov@gmail.com>

Validate the service pipe to avoid connecting to a bogus pipe

---

localization.c
openvpn-gui-res.h
openvpn.c
options.h
registry.c
res/openvpn-gui-res-cs.rc
res/openvpn-gui-res-de.rc
res/openvpn-gui-res-dk.rc
res/openvpn-gui-res-en.rc
res/openvpn-gui-res-es.rc
res/openvpn-gui-res-fa.rc
res/openvpn-gui-res-fi.rc
res/openvpn-gui-res-fr.rc
res/openvpn-gui-res-it.rc
res/openvpn-gui-res-jp.rc
res/openvpn-gui-res-kr.rc
res/openvpn-gui-res-nl.rc
res/openvpn-gui-res-no.rc
res/openvpn-gui-res-pl.rc
res/openvpn-gui-res-pt.rc
res/openvpn-gui-res-ru.rc
res/openvpn-gui-res-se.rc
res/openvpn-gui-res-tr.rc
res/openvpn-gui-res-ua.rc
res/openvpn-gui-res-zh-hans.rc
res/openvpn-gui-res-zh-hant.rc

This is more like a quick solution for user requests such as #663.
This is built on top of #701, by adding a global option to always prompt for OTP and submit it concatenated with password. Submitting as a separate PR as I'm not fully convinced of the need for this.
The newly extended static-challenge config option (GUI support is in PR #701)  that can optionally specify concatenation format should be preferred over this. Always prompting for OTP could confuse users when none are required.  But the former will be available only in OpenVPN 2.7 while this is immediately usable.

Add a global option to always prompt for OTP

---

CHANGES.rst
tray.c

Fix position of the tray icon info tip when the taskbar is at the top of the screen

---

localization.c

`Int32x32To64` macro internally truncates the arguments to int32, while `time_t` is 64-bit on most/all modern platforms. Therefore, usage of this macro creates a Year 2038 bug.
I detailed this issue a while ago in a writeup, and spotted the same issue in this repository when updating the list of affected repositories:
<https://cookieplmonster.github.io/2022/02/17/year-2038-problem/>

Fix a Y2038 bug by replacing `Int32x32To64` with regular multiplication

---

.git-blame-ignore-revs

This allows one to ignore the project-wide reformats for the purposes of git blame.
File comment copied from openvpn.

Add input file for git blame --ignore-revs-file

---

openvpn_config.c
options.h
tray.c

Since the introduction of persistent connections, we no longer recreate the entire config menu but only add newly added connection profiles during each rescan. This leaves any deleted configs actively displayed in the menu until the GUI is restarted.
Improve this situation by graying out entries corresponding to profiles not readable from file system. If the file reappears, the item gets automatically enabled again.
Also, if the corresponding connection is active, the item is not grayed out to allow the user to disconnect or reconnect it. Otherwise the corresponding OpenVPN core process will hang around with no way to control it from the GUI. Here "active" includes those on management-hold in case of persistent connections, as those can be started even if the underlying config file has …

Disable config in menu listing if its ovpn file becomes inaccessible

---

main.c
main.h

C:\\windows\\Temp\\ has been write-protected since a while, so instead of hardcoding the (wrong) path, use GetTempPath().

Use correct %TEMP% directory for log file

---

openvpn.c

When CR_TEXT or dynamic CR prompt is triggered with 'response not required' ('R' not present in flags), we hide the response box, but not the password reveal eye icon. Fix it.
Avoids this lonely eye:

Hide password reveal eye icon when no response box is shown

---

res/openvpn-gui-res-tr.rc

Sorry for being late.
This commit significantly improves the Turkish localization of the OpenVPN GUI by 
translating numerous strings that were previously in English. The changes include:
1. User Interface Elements:
- Translated all remaining English text in dialog boxes
- Properly localized checkbox and button labels
- Updated radio button text to Turkish
- Improved existing translations for better clarity
2. Dialog Box Translations:
- Passphrase Dialog: Translated "Save password" to "Şifreyi Kaydet"
- Authentication Dialog: Translated remaining English elements
- Advanced Dialog: Fully translated all configuration options
- General Settings: Translated UI preferences and options
- URL Profile Import: Localized all elements
3. Menu Items:
- Translated all import-related menu options
- …

Improve Turkish (tr) localization for OpenVPN GUI
